services:
  postgres:
    image: postgres:15
    container_name: db_medical_app
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: medical_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest
    container_name: api_medical_app
    depends_on:
      - postgres
    restart: always
    environment:
      PGRST_DB_URI: "postgres://admin:adminpassword@postgres:5432/medical_db"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_DB_SCHEMA: "public"
      PGRST_JWT_SECRET: "V4X9N1GpQzFvZDhKRWpTeUJQYnVmVlpvTmRxSmw3dUtZbTRKcEZLeHdLMHRaM0Nx"
      PGRST_SERVER_PORT: 3000
    ports:
      - "3000:3000"

volumes:
  db_data:
